config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :questions, except: [] do
    resources :answers, only:[:new, :create, :index]
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :description, presence: true, length: {minimum: 50}

  belongs_to :question

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 40}
  validates :detail, presence: true, length: {minimum: 150}

  has_many :answers, dependent: :destroy

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
    @question = Question.find(params[:question_id])
    @answers = @question.answers.order(created_at: :asc)
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question = @question
    if @answer.save
      flash[:notice] = "Question answered!"
      redirect_to question_path(@question)
    else
      flash[:notice] = @answer.errors.full_messages
      render 'questions/show'
    end
  end

  protected

  def answer_params
    params.require(:answer).permit(:description)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all.order(created_at: :desc)
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = @question.answers.order(created_at: :asc)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = 'Question added.'
      redirect_to root_path
    else
      flash[:notice] = @question.errors.full_messages
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update(question_params)
    if @question.save
      flash[:notice] = 'Question revised.'
      redirect_to question_path(@question)
    else
      flash[:notice] = @question.errors.full_messages
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    flash[:notice] = 'Question deleted.' if @question.destroy
    redirect_to questions_path
  end

  protected

  def question_params
    params.require(:question).permit(:title, :detail)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/index.html.erb
<% markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML) %>

<% unless @answers == [] || @answers.nil? %>
  <h3 class="subheader">Answers</h3>
  <ul id="all_answers">
    <% @answers.each do |answer| %>
      <li><%= markdown.render(answer.description).html_safe%></li>
    <% end %>
  </ul>
<% end %>

app/views/answers/new.html.erb
<h3 class="subheader">Do you have an answer?</h3>
<%= form_for [@question, @answer] do |f| %>
  <%= f.label :description, "Answer" %>
  <%= f.text_field :description %>
  <%=f.submit "Answer Question" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash.any? %>
  <div class="flash">
    <div class="top-bar" id="flash">
      <%if flash[:notice].is_a?(Array) %>
        <ul>
          <% flash[:notice].each do |notice| %>
            <li><%= notice %></li>
          <% end %>
        </ul>
      <% else %>
        <%= flash[:notice] %>
      <% end %>
    </div>
  </div>
<% end %>

<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Rescue Mission", root_path, class: "title"%></h1>
    </li>
  </ul>
</nav>

<div class="container">
  <div class="row">
    <div class="column">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/questions/edit.html.erb
    <h1>Revise Question</h1>

    <%= form_for @question do |f| %>
      <h2><%= f.label :title %></h2>
      <%= f.text_field :title %>

      <h2><%= f.label :detail %></h2>
      <%= f.text_area :detail %>

      <%=f.submit "Submit Revision" %>
    <% end %>

  <%= link_to "Actually, just delete this", question_path(@question),
    method: :delete %>

app/views/questions/index.html.erb
<header><h1>All Questions</h1><header>

<div class="container">
  <ul id="all_questions">
    <% @questions.each do |question| %>
      <li>
        <a href="questions/<%= question.id %>"><%= question.title %></a>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to "Ask a new question", new_question_path, class: "button radius" %>

app/views/questions/new.html.erb
<div class="large-12">
  <h1>New Question</h1>

  <%= form_for @question do |f| %>
    <h2><%= f.label :title %></h2>
    <%= f.text_field :title %>

    <h2><%= f.label :detail %></h2>
    <%= f.text_area :detail %>

    <%=f.submit "Submit Question" %>
  <% end %>
</div>

app/views/questions/show.html.erb
<% markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML) %>

<div="row" id="title_block">
  <div="column">
    <h1><%= markdown.render(@question.title).html_safe %><h1>
  </div>
</div>

<div="row" id="detail_block">
  <div="column">
    <h2 class="subheader">Details:</h2>
    <%= markdown.render(@question.detail).html_safe%>
  </div>
</div>

<%= link_to "Revise Question", edit_question_path(@question) %>  </div>
<%= link_to "Delete Question", question_path(@question), method: :delete %>

<div class="row">
  <%= render template: 'answers/index' %>
</div>

<div class="row">
  <%= render template: 'answers/new' %>
</div>